export const devHexagon = {
  boardHexes: {
    '-3,0,3': {
      q: -3,
      r: 0,
      s: 3,
      id: '-3,0,3',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['0', '5'],
    },
    '-3,1,2': {
      q: -3,
      r: 1,
      s: 2,
      id: '-3,1,2',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['0', '5'],
    },
    '-3,2,1': {
      q: -3,
      r: 2,
      s: 1,
      id: '-3,2,1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['2', '5'],
    },
    '-3,3,0': {
      q: -3,
      r: 3,
      s: 0,
      id: '-3,3,0',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['2', '5'],
    },
    '-2,-1,3': {
      q: -2,
      r: -1,
      s: 3,
      id: '-2,-1,3',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['0', '5'],
    },
    '-2,0,2': {
      q: -2,
      r: 0,
      s: 2,
      id: '-2,0,2',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['0', '5'],
    },
    '-2,1,1': {
      q: -2,
      r: 1,
      s: 1,
      id: '-2,1,1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'sand',
      startzonePlayerIDs: ['5'],
    },
    '-2,2,0': {
      q: -2,
      r: 2,
      s: 0,
      id: '-2,2,0',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['2', '5'],
    },
    '-2,3,-1': {
      q: -2,
      r: 3,
      s: -1,
      id: '-2,3,-1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['2', '5'],
    },
    '-1,-2,3': {
      q: -1,
      r: -2,
      s: 3,
      id: '-1,-2,3',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['0', '3'],
    },
    '-1,-1,2': {
      q: -1,
      r: -1,
      s: 2,
      id: '-1,-1,2',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['0'],
    },
    '-1,0,1': {
      q: -1,
      r: 0,
      s: 1,
      id: '-1,0,1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: [],
    },
    '-1,1,0': {
      q: -1,
      r: 1,
      s: 0,
      id: '-1,1,0',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: [],
    },
    '-1,2,-1': {
      q: -1,
      r: 2,
      s: -1,
      id: '-1,2,-1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['2'],
    },
    '-1,3,-2': {
      q: -1,
      r: 3,
      s: -2,
      id: '-1,3,-2',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['1', '2'],
    },
    '0,-3,3': {
      q: 0,
      r: -3,
      s: 3,
      id: '0,-3,3',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['0', '3'],
    },
    '0,-2,2': {
      q: 0,
      r: -2,
      s: 2,
      id: '0,-2,2',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['0', '3'],
    },
    '0,-1,1': {
      q: 0,
      r: -1,
      s: 1,
      id: '0,-1,1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: [],
    },
    '0,0,0': {
      q: 0,
      r: 0,
      s: 0,
      id: '0,0,0',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 1,
      terrain: 'grass',
      startzonePlayerIDs: [],
    },
    '0,1,-1': {
      q: 0,
      r: 1,
      s: -1,
      id: '0,1,-1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: [],
    },
    '0,2,-2': {
      q: 0,
      r: 2,
      s: -2,
      id: '0,2,-2',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['1', '2'],
    },
    '0,3,-3': {
      q: 0,
      r: 3,
      s: -3,
      id: '0,3,-3',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['1', '2'],
    },
    '1,-3,2': {
      q: 1,
      r: -3,
      s: 2,
      id: '1,-3,2',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['0', '3'],
    },
    '1,-2,1': {
      q: 1,
      r: -2,
      s: 1,
      id: '1,-2,1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['3'],
    },
    '1,-1,0': {
      q: 1,
      r: -1,
      s: 0,
      id: '1,-1,0',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: [],
    },
    '1,0,-1': {
      q: 1,
      r: 0,
      s: -1,
      id: '1,0,-1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: [],
    },
    '1,1,-2': {
      q: 1,
      r: 1,
      s: -2,
      id: '1,1,-2',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['1'],
    },
    '1,2,-3': {
      q: 1,
      r: 2,
      s: -3,
      id: '1,2,-3',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['1', '2'],
    },
    '2,-3,1': {
      q: 2,
      r: -3,
      s: 1,
      id: '2,-3,1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['3', '4'],
    },
    '2,-2,0': {
      q: 2,
      r: -2,
      s: 0,
      id: '2,-2,0',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['3', '4'],
    },
    '2,-1,-1': {
      q: 2,
      r: -1,
      s: -1,
      id: '2,-1,-1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['4'],
    },
    '2,0,-2': {
      q: 2,
      r: 0,
      s: -2,
      id: '2,0,-2',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['1', '4'],
    },
    '2,1,-3': {
      q: 2,
      r: 1,
      s: -3,
      id: '2,1,-3',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['1', '4'],
    },
    '3,-3,0': {
      q: 3,
      r: -3,
      s: 0,
      id: '3,-3,0',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['3', '4'],
    },
    '3,-2,-1': {
      q: 3,
      r: -2,
      s: -1,
      id: '3,-2,-1',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['3', '4'],
    },
    '3,-1,-2': {
      q: 3,
      r: -1,
      s: -2,
      id: '3,-1,-2',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['1', '4'],
    },
    '3,0,-3': {
      q: 3,
      r: 0,
      s: -3,
      id: '3,0,-3',
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 6,
      terrain: 'grass',
      startzonePlayerIDs: ['1', '4'],
    },
  },
  hexMap: {
    mapId: 'devHexagon',
    mapShape: 'hexagon',
    mapName: 'Dev Hexagon',
    flat: false,
    mapSize: 3,
    hexSize: 10,
    mapWidth: 3,
    mapHeight: 3,
    glyphs: {
      '-3,3,0': {
        hexID: '-3,3,0',
        glyphID: 'move',
        isRevealed: true,
      },
      '0,0,0': {
        hexID: '0,0,0',
        glyphID: 'defense',
        isRevealed: false,
      },
    },
  },
}
