export const moveRange1HexFlyEngagedMapTestHexIDs = {
  enemyUnit1: '1,0,-1',
  movingUnit2: '0,0,0',
  enemyUnit2: '-1,0,1',
  adjacentHex: '0,-1,1',
}

export const moveRange1HexFlyEngagedMap = {
  boardHexes: {
    [moveRange1HexFlyEngagedMapTestHexIDs.movingUnit2]: {
      q: 0,
      r: 0,
      s: 0,
      id: moveRange1HexFlyEngagedMapTestHexIDs.movingUnit2,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 1,
      terrain: 'grass',
      startzonePlayerIDs: ['1'],
    },
    [moveRange1HexFlyEngagedMapTestHexIDs.enemyUnit1]: {
      q: 1,
      r: 0,
      s: -1,
      id: moveRange1HexFlyEngagedMapTestHexIDs.enemyUnit1,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 1,
      terrain: 'grass',
      startzonePlayerIDs: ['0'],
    },
    [moveRange1HexFlyEngagedMapTestHexIDs.enemyUnit2]: {
      q: -1,
      r: 0,
      s: 1,
      id: moveRange1HexFlyEngagedMapTestHexIDs.enemyUnit2,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 1,
      terrain: 'grass',
      startzonePlayerIDs: ['0'],
    },
    [moveRange1HexFlyEngagedMapTestHexIDs.adjacentHex]: {
      q: 0,
      r: -1,
      s: 1,
      id: moveRange1HexFlyEngagedMapTestHexIDs.adjacentHex,
      occupyingUnitID: '',
      isUnitTail: false,
      altitude: 1,
      terrain: 'grass',
      startzonePlayerIDs: [''],
    },
  },
  hexMap: {
    mapId: 'moveRange1HexFlyEngagedMap',
    mapShape: 'hexagon',
    mapName: 'Move Range 1-Hex Fly Engaged Test Map',
    flat: false,
    mapSize: 1,
    hexSize: 10,
    mapWidth: 1,
    mapHeight: 1,
    glyphs: {},
  },
}
