const myFile = {
  version: 0.0007,
  name: '',
  author: '',
  playerNumber: '',
  scenario: '',
  levelPerPage: 6,
  printingTransparency: 80,
  printingGrid: true,
  printTileNumber: false,
  printStartAreaAsLevel: true,
  tileCount: 1,
  tiles: [
    {
      type: 18001,
      version: 0.0003,
      rotation: 0,
      posX: 0,
      posY: 0,
      posZ: 0,
      glyphLetter: '\u0000',
      glyphName: '',
      startName: '',
      colorf: 16777215,
      isPersonalTile: false,
      personal: {
        pieceSize: 0,
        textureTop: '',
        textureSide: '',
        letter: '',
        name: '',
      },
    },
  ],
}
